# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='destination_city',
            field=models.CharField(default='Kyiv', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='from_city',
            field=models.CharField(default='Glevaha', max_length=255),
            preserve_default=False,
        ),
    ]
